pipeline {
  agent any
  
      parameters {
      string(name: 'inventory', defaultValue: 'dev.yml',  description: 'This is the inventory file for the environment to deploy configuration')
    }

  environment {
    ANSIBLE_CONFIG="${WORKSPACE}/deploy/ansible.cfg"
  }

  stages{
    stage("Initial cleanup") {
      steps {
        dir("${WORKSPACE}") {
          deleteDir()
        }
      }
    }
  
    stage(" Checkout SCM") {
      steps {
        git branch: 'main', url: 'https://github.com/oayanda/ansible-configuration.git'
      }
    }

    stage("Prepare Ansible For Execution") {
      steps {
        sh 'echo ${WORKSPACE}' 
        sh 'sed -i "3 a roles_path=${WORKSPACE}/roles" ${WORKSPACE}/deploy/ansible.cfg' 
      }
    }

    stage('Run Ansible playbook') {
        steps {
           ansiblePlaybook become: true, colorized: true, credentialsId: 'ansible-key', disableHostKeyChecking: true, installation: 'Ansible-pip', inventory: 'inventory/${inventory}', playbook: 'playbooks/site.yml'
         }
      }

    stage('Clean Workspace after build'){
        steps{
          cleanWs()
        }
      }
 }

}